main/urls.py
from django.urls import path
from main.views import add_product_ajax, get_product_json, show_main, create_product, show_xml, show_json, show_json_by_id, show_xml_by_id
from main.views import register, login_user, logout_user
from main.views import edit_product, delete_product
from main.views import delete_product_ajax
app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('create-product', create_product, name='create_product'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('edit-product/<int:id>', edit_product, name='edit_product'),
    path('delete-product/<int:id>', delete_product, name='delete_product'),
    path('get-product/', get_product_json, name='get_product_json'),
    path('create-product-ajax/', add_product_ajax, name='add_product_ajax'),
    path('delete-product-ajax/', delete_product_ajax, name='delete_product_ajax'),
]

scud_inventory/urls.py
from django.contrib import admin
from django.urls import path, include
from django.urls import path

# urlpatterns = [
#     path('admin/', admin.site.urls),
#     path('main/', include('main.urls')),
# ]

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include ('main.urls')),
    path('admin/', admin.site.urls),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User

class Product(models.Model):
    name = models.CharField(max_length=255)
    date_added = models.DateField(auto_now_add=True)
    amount = models.IntegerField()
    description = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)

main/forms.py
from django.forms import ModelForm
from main.models import Product

class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = ["name", "amount", "description"]

main/views.py
from django.shortcuts import render
from django.http import HttpResponseNotFound, HttpResponseRedirect
from main.forms import ProductForm
from django.urls import reverse
from main.models import Product
from django.http import HttpResponse
from django.core import serializers
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt

# Create your views here.


@login_required(login_url='/login')
def show_main(request):
    products = Product.objects.filter(user=request.user)

    context = {
        'name': request.user.username,
        'class': 'PBP A',
        'products': products,
        'last_login': request.COOKIES['last_login'],
    }

    return render(request, "main.html", context)


def create_product(request):
    form = ProductForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        product = form.save(commit=False)
        product.user = request.user
        product.save()
        return HttpResponseRedirect(reverse('main:show_main'))
    context = {
        'form': form,
        'name': request.user.username,
    }
    return render(request, "create_product.html", context)


def show_xml(request):
    data = Product.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")


def show_json(request):
    data = Product.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")


def show_xml_by_id(request, id):
    data = Product.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")


def show_json_by_id(request, id):
    data = Product.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")


def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(
                request, 'Your account has been successfully created!')
            return redirect('main:login')
    context = {'form': form}
    return render(request, 'register.html', context)


def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("main:show_main"))
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.info(
                request, 'Sorry, incorrect username or password. Please try again.')
    context = {}
    return render(request, 'login.html', context)


def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return response


def edit_product(request, id):
    product = Product.objects.get(pk=id)

    form = ProductForm(request.POST or None, instance=product)

    if form.is_valid() and request.method == "POST":
        form.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {
        'form': form,
        'name': request.user.username,
    }
    return render(request, "edit_product.html", context)


def delete_product(request, id):
    product = Product.objects.get(pk=id)
    product.delete()
    return HttpResponseRedirect(reverse('main:show_main'))

def get_product_json(request):
    product_item = Product.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize('json', product_item))

@csrf_exempt
def add_product_ajax(request):
    if request.method == 'POST':
        name = request.POST.get("name")
        amount = request.POST.get("amount")
        description = request.POST.get("description")
        user = request.user

        new_product = Product(name=name, amount=amount, description=description, user=user)
        new_product.save()

        return HttpResponse(b"CREATED", status=201)

    return HttpResponseNotFound()

@csrf_exempt
def delete_product_ajax(request):
    if request.method == 'POST':
        id = request.POST.get('id')
        product = Product.objects.get(pk=id)
        product.delete()
        return HttpResponse(b"OK", status=200)

    return HttpResponseNotFound()

main/templates/create_product.html
{% extends 'base.html' %} 

{% block content %}
<h1>Add New Product</h1>

<form method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
        <tr>
            <td></td>
            <td>
                <input type="submit" value="Add Product"/>
            </td>
        </tr>
    </table>
</form>

{% endblock %}

main/templates/edit_product.html
{% extends 'base.html' %}

{% block meta %}
    <title>Edit Product</title>
{% endblock meta %}

{% block content %}
<style>
    body {
        background-color: #64CCC5;
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100vh;
    }

    .edit-product {
        background-color: #DAFFFB; 
        padding: 20px;
        border-radius: 10px;
        width: 400px; /* Lebih besar */
        text-align: center;
    }

    .edit-product h1 {
        font-size: 28px; /* Ukuran huruf lebih besar */
        margin-bottom: 20px;
    }

    .edit-product .mb-3 {
        margin-bottom: 15px;
    }

    .edit-product input.form-control {
        width: 100%;
    }

    .edit-product .btn.edit_btn {
        width: 100%;
        background-color: #64CCC5; /* Warna biru */
        color: black;
        border: none;
    }

    .edit-product .btn.edit_btn:hover {
        background-color: #0056b3; 
    }

    .edit-product p {
        font-size: 14px; /* Ukuran teks lebih kecil */
        margin-top: 20px;
    }
</style>

<div class="edit-product">
    <h1 class="h3 mb-3 fw-normal">Edit Product</h1>

    <form method="POST">
        {% csrf_token %}
        <div class="mb-3">
            {{ form.as_p }}
        </div>

        <button class="btn btn-primary w-100 py-2 edit_btn" type="submit">Edit Product</button>
    </form>
</div>
{% endblock content %}

main/templates/login.html
{% extends 'base.html' %}

{% block meta %}
    <title>Login</title>
{% endblock meta %}

{% block content %}
<style>
    body {
        background-color: #176B87; 
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100vh;
    }

    .login {
        background-color: #64CCC5; 
        padding: 20px;
        border-radius: 10px;
        width: 300px;
        text-align: center;
    }

    .login h1 {
        font-size: 28px; /* Ukuran huruf lebih besar */
        margin-bottom: 20px;
    }

    .login .mb-3 {
        margin-bottom: 15px;
    }

    .login input.form-control {
        width: 100%;
    }

    .login .btn.login_btn {
        width: 100%;
        background-color: #007bff; /* Warna biru */
        color: white;
        border: none;
    }

    .login .btn.login_btn:hover {
        background-color: #0056b3; /* Warna biru yang lebih gelap saat menghover */
    }

    .login p {
        font-size: 14px; /* Ukuran teks  */
        margin-top: 20px;
    }
</style>

<div class="login">
    <h1 class="h3 mb-3 fw-normal">Please Login</h1>

    <form method="POST" action="">
        {% csrf_token %}
        <div class="mb-3">
            <label for="username" class="form-label">Username</label>
            <input type="text" name="username" placeholder="Username" class="form-control" id="username">
        </div>

        <div class="mb-3">
            <label for="password" class="form-label">Password</label>
            <input type="password" name="password" placeholder="Password" class="form-control" id="password">
        </div>

        <button class="btn btn-primary w-100 py-2" type="submit">Login</button>
    </form>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}     
        
    Don't have an account yet? <a href="{% url 'main:register' %}">Register Now</a>
</div>
{% endblock content %}

main/templates/main.html
{% extends 'base.html' %}

{% block content %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Your Page Title</title>
    <style>
        .centered-container {
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
        }

        .main-container {
            margin: 50px;
        }

        h1 {
            text-align: center;
        }

        table {
            width: 100%;
            border-collapse: collapse;
        }

        table,
        th,
        td {
            border: 1px solid black;
        }

        th,
        td {
            padding: 8px;
        }

        th {
            background-color: #f2f2f2;
        }

        tr.table-row:last-child {
            background-color: #8deebd;
        }

        .navbar-fixed {
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            z-index: 1000;
        }
    </style>
</head>

<nav class="navbar navbar-fixed bg-dark">
    <div class="container-fluid">
        <span class="navbar-brand mb-0 h1 text-white">Hi, {{ name }}!</span>
        <a href="{% url 'main:logout' %}">
            <button>
                Logout
            </button>
        </a>
    </div>
</nav>

<body>
    <div class="main-container">
        <div class="centered-container">
            <h1>Shop Inventory</h1>
        </div>

        <div class="left-align">
            <h5>Name:</h5>
            <p>{{name}}</p>

            <h5>Class:</h5>
            <p>{{class}}</p>
        </div>

        <div class="centered-container">
            <table id="product_table"></table>
        </div>
        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h1 class="modal-title fs-5" id="exampleModalLabel">Add New Product</h1>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <form id="form" onsubmit="return false;">
                            {% csrf_token %}
                            <div class="mb-3">
                                <label for="name" class="col-form-label">Name:</label>
                                <input type="text" class="form-control" id="name" name="name"></input>
                            </div>
                            <div class="mb-3">
                                <label for="amount" class="col-form-label">Amount:</label>
                                <input type="number" class="form-control" id="amount" name="amount"></input>
                            </div>
                            <div class="mb-3">
                                <label for="description" class="col-form-label">Description:</label>
                                <textarea class="form-control" id="description" name="description"></textarea>
                            </div>
                        </form>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        <button type="button" class="btn btn-primary" id="button_add" data-bs-dismiss="modal">Add
                            Product</button>
                    </div>
                </div>
            </div>
        </div>
        <br />

        <div class="left-align">
            <h5>Sesi terakhir login: {{ last_login }}</h5>
        </div>

        <div class="left-align">
            <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">Add
                Product</button>
        </div>
    </div>
</body>

</html>

<script>
    async function getProducts() {
        return fetch("{% url 'main:get_product_json' %}").then((res) => res.json())
    }

    async function refreshProducts() {
        document.getElementById("product_table").innerHTML = ""
        const products = await getProducts()
        let htmlString = `<tr>
            <th>Name</th>
            <th>Amount</th>
            <th>Description</th>
            <th>Date Added</th>
            <th></th>
        </tr>`
        products.forEach((item) => {
            htmlString += `\n<tr>
            <td>${item.fields.name}</td>
            <td>${item.fields.amount}</td>
            <td>${item.fields.description}</td>
            <td>${item.fields.date_added}</td>
            <td><button onclick="deleteProduct(${item.pk})">Delete</button></td>
        </tr>`
        })

        document.getElementById("product_table").innerHTML = htmlString
    }

    refreshProducts()
    function addProduct() {
        fetch("{% url 'main:add_product_ajax' %}", {
            method: "POST",
            body: new FormData(document.querySelector('#form'))
        }).then(refreshProducts)

        document.getElementById("form").reset()
        return false
    }
    document.getElementById("button_add").onclick = addProduct

    function deleteProduct(id) {
        fetch("{% url 'main:delete_product_ajax' %}", {
            method: "POST",
            headers: {
                'X-CSRFToken': '{{ csrf_token }}',
                'Content-Type': 'application/x-www-form-urlencoded'
            },
            body: `id=${id}`
        }).then(refreshProducts()
        );
    }
</script>
{% endblock content %}

main/templates/register.html
{% extends 'base.html' %}

{% block meta %}
    <title>Register</title>
{% endblock meta %}

{% block content %}
<style>
    body {
        background-color: #176B87; /* Latar belakang biru */
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100vh;
        
    }

    .register {
        background-color: #64CCC5; 
        padding: 20px;
        border-radius: 10px;
        width: 300px;
        text-align: center;
    }

    .register h1 {
        font-size: 28px;
        margin-bottom: 20px;
    }

    .register .mb-3 {
        margin-bottom: 15px;
    }

    .register input.form-control {
        width: 100%;
    }

    .register .btn.register_btn {
        width: 100%;
        background-color: #007bff; 
        color: white;
        border: none;
    }

    .register .btn.register_btn:hover {
        background-color: #0056b3; 
    }

    .register p {
        font-size: 14px; /* Ukuran teks lebih kecil */
        margin-top: 20px;
    }
</style>

<div class="register">
    <h1 class="h3 mb-3 fw-normal">Register</h1>

    <form method="POST">
        {% csrf_token %}
        <div class="mb-3">
            {{ form.as_p }}
        </div>

        <button class="btn btn-primary w-100 py-2 register_btn" type="submit">Register</button>
    </form>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
</div>
{% endblock content %}

main/templates/templates.html
   <!DOCTYPE html>
    <html>
    

    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Fira+Sans+Condensed:wght@300&family=Libre+Baskerville:ital@0;1&display=swap" rel="stylesheet">
    <head>
      <title>CSS Display Property Example</title>
      <style>
            body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f2f2f2;
            min-height: 100vh;
            display: flex;
            flex-direction: column;
            align-items: center;
        }

        .title {
            font-size: 24px;
            font-weight: bold;
            margin: 20px 0;
            font-family: 'Fira Sans Condensed', sans-serif; font-family: 'Libre Baskerville', serif;
            font-size: 50px;
        }

        .container {
            display: flex;
            justify-content: space-between;
            align-items: flex-start; 
            background-color: #ffffff;
            box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.2);
            padding: 20px;
            width: 80%;
            margin: 20px 0;
        }

        .item-card {
            text-align: center;
            flex: 0 0 30%; 
            margin: 0 10px;
            display: flex;
            flex-direction: column;
            height: 100%; 
        }

        .item-card img {
            max-width: 100%;
            height: auto;
        }

        .item-card .card-description {
            flex-grow: 1;
            text-align: justify; 
        }

        .item-card .card-button {
            background-color: #007bff;
            color: #ffffff;
            padding: 10px 20px;
            border: none;
            cursor: pointer;
        }

        .placeholders {
            display: flex;
            justify-content: flex-start;
            align-items: flex-end;
            background-color: #ffffff;
            padding: 20px;
            width: 80%;
            margin-top: 20px;
        }

        .placeholder {
            width: 100px;
            height: 100px;
            background-color: #cccccc;
            border-radius: 50%;
            margin-right: 10px; 
            overflow: hidden;
        }

        .placeholder img {
            width: 100%;
            height: 100%;

            object-fit: cover;
        }

        .team {
            font-weight: bold;
            margin-top: 10px;
            text-align: right; 
            flex-grow: 1; 
            font-size: 25px;
        }
      </style>
    </head>
    
    
    <body>
        <div class="title">Herta's Store</div>
        <div style="font-size: 25px;">Your Cosmic Fragments: {{ amount }}</div>
    
        <div class="container">
            <div class="item-card">
                <h2>Black Hole Trap</h2>
                <img src="templates/curio2.jpg" alt="Gambar Item 1">
                <p class="card-description">{{description3}}</p>
                <button class="card-button">Confirm</button>
            </div>
    
            <div class="item-card">
                <h2>Tonic of Chaos</h2>
                <img src="templates/curio1.jpg" alt="Gambar Item 2">
                <p class="card-description">{{description2}}</p>
                <button class="card-button">Confirm</button>
            </div>
    
            <div class="item-card">
                <h2>Black Hole Trap</h2>
                <img src="templates/curio3.jpg" alt="Gambar Item 3">
                <p class="card-description">{{description1}}.</p>
                <button class="card-button">Confirm</button>
            </div>
            
        </div>
    
        <div class="placeholders">
            <div class="placeholder">
                <img src="templates/chara1.jpg" alt="Gambar Item 3">
                
            </div>
            <div class="placeholder">
    
                <img src="templates/chara2.jpg" alt="Gambar Item 3">
            </div>
            <div class="placeholder">
                <img src="templates/chara3.jpg" alt="Gambar Item 3">
            </div>
            <div class="placeholder">
                <img src="templates/chara4.jpg" alt="Gambar Item 3">
            </div>
            <div class="team">{{ name }}Team</div>
        </div>
    </body>
    </html>
    

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        {% block meta %}
            <meta charset="UTF-8" />
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
            <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha384-KyZXEAg3QhqLMpG8r+J4jsl5c9zdLKaUk5Ae5f5b1bw6AUn5f5v8FZJoMxm6f5cH1" crossorigin="anonymous"></script>
            <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
        {% endblock meta %}
    </head>

    <body>
        {% block content %}
        {% endblock content %}
    </body>
</html>